#!/usr/bin/env zsh
#
#
# === {{CMD}}
# === {{CMD}} watch
#

if [[ -z "$@" ]]; then
  local +x ACTION="default"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in
  default)
    ping google.com -c 1 -w 9 &>/dev/null
    ping 8.8.8.8 -c 1 -w 9 &>/dev/null
    ;;

  ipv4)
    ping -4 8.8.8.8 -c 1 -w 3 &>/dev/null
    ;;

  ipv6)
    ping -6 google.com -c 1 -w 3 &>/dev/null
    ;;

  --verbose)
    local +x IS_CONN="yes"
    if my_network is-connected ipv6 ; then
      echo "=== ipv6 up"
    else
      echo "!   ipv6 down"
      IS_CONN="no"
    fi
    if my_network is-connected ipv4 ; then
      echo "=== ipv4 up"
    else
      echo "!   ipv4 down"
      IS_CONN="no"
    fi
    if test "$IS_CONN" = "yes" ; then
      exit 0
    fi
    exit 1
    ;;

  watch)
    date +"%c"
    my_network is-connected --verbose || :
    local +x is_conn="yes"
    while true ; do
      if my_network is-connected ipv6 ; then
        echo -n "."
      else
        echo -n "x"
        is_conn="no"
      fi
      if my_network is-connected ipv4 ; then
        echo -n "."
      else
        echo -n "x"
        is_conn="no"
      fi
      if test "$is_conn" = "yes" ; then
        echo ""
        sh_color GREEN "=== {{Connected}} to the Internet: $(date +"%c") ==="
        mpv "$THIS_DIR"/solemn.ogg &>/dev/null
        exit 0
      else
        echo -n " "
        sleep 2
      fi
    done
    ;;
esac
