#!/usr/bin/env zsh
#
#
# === {{CMD}}
# === {{CMD}} watch
#

if [[ -z "$@" ]]; then
  local +x ACTION="default"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in
  default)
    ping 8.8.4.4 -c 1 -w 2 &>/dev/null
    ;;

  watch)
    date +"%c"
    while ! my_network is-connected; do
      echo -n "."
      sleep 2
    done
    echo
    sh_color GREEN "=== {{Connected}} to the Internet: $(date +"%c") ==="
    mpv "$THIS_DIR"/solemn.ogg &>/dev/null
    ;;
esac
