#!/usr/bin/env zsh
#
#
# === {{CMD}} watch
#

local +x ACTION="$1"; shift

case "$ACTION" in
  watch)
    while ! ping 8.8.4.4 -c 1 -w 2 &>/dev/null; do
      echo -n "."
      sleep 2
    done
    echo
    sh_color GREEN "=== {{Connected}} to the Internet. ==="
    ;;

esac
